Feature/p2022 1259 integration witch the backend
intive/patronage22-android-lublin pull request #23
Opened 2022-04-02 20:49 UTC by michalfiuk1

# [P2022-1259](https://tracker.intive.com/jira/browse/P2022-1259)

## PROBLEM
Integration with the backend

## SOLUTION
Add the required life cycle dependencies.
Create an enum class to represent UI State.(enum class **Status**)
Create a utility class that will be responsible to communicate the current state of Network Call to the UI Layer.(data class **Resource**)
Change ProductApi to the corresponding response data from the URL (adding a category for an additional tab operation).
Removing repositories and mappers corresponding to database mocking from local files.
Adding fun setupViewModel and Observer to Fragment Category / Home in order to initialize Retrofit and update information about loaded data and send appropriate status.
Creation of the ViewModel instance and factory.

## SCREENSHOTS

## SIDE NOTES
Using https://mockapi.io/ as baseURL until [link]([http://proxy-patronageapi.bsolutions.usermd.net/api/](http://proxy-patronageapi.bsolutions.usermd.net/api/products/getAllProductsExternal)) is broken.

2022-04-03 15:10 UTC, dziubinski-intive approved these changes

2022-04-03 15:11 UTC, dziubinski-intive requested changes
Approved by mistake

2022-04-03 15:15 UTC, dziubinski-intive commented
@michalfiuk1 did you confirm API structure with someone or you just adopted model to random Product list response?

A lot of files are marked as remove & added. Personally thought we will just change mapper according to new API model.

2022-04-03 15:35 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/screens/categories/CategoriesFragment.kt
> +    private fun setupViewModel() {
please use by viewModels delegate:

```
    private val factory = ViewModelFactory(ApiHelper(RetrofitBuilder.apiService))
    private val viewModel: CategoriesViewModel by viewModels { factory }
```

Ideally ViewModelFactory should be injected.

2022-04-04 10:46 UTC, michalfiuk1 commented on app/src/main/java/com/intive/patronage22/lublin/screens/categories/CategoriesFragment.kt
> +    private fun setupViewModel() {
> @michalfiuk1 did you confirm API structure with someone or you just adopted model to random Product list response?

I use the answers from the backend: [answer](http://proxy-patronageapi.bsolutions.usermd.net/api/products/getAllProductsExternal)

2022-04-04 11:09 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/repository/mapper/ProductListMapper.kt
> +                photoUrl = response.photosList.find { it.isMainPhoto }?.url ?: ""
as long as we may have multiple photos required, would rename it to `mainPhotoUrl`

2022-04-04 11:10 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/repository/model/GetProductResponse.kt
> +data class Photo(
would add `Api` suffix to network models to avoid mistakes later as long as we are within the same module.

2022-04-04 11:11 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/repository/mapper/ListMapper.kt
> +interface ListMapper<From, To> {
think we can drop this interface as it doesn't bring any value here

2022-04-04 11:12 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/repository/model/GetProductResponse.kt
> +data class GetProductResponse(
can it be `@Parcelize` as well?

2022-04-04 11:12 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/repository/model/GetProductResponse.kt
> +    @SerializedName("title")
for custom names we can use `@JsonProperty`

2022-04-05 07:50 UTC, michalfiuk1 commented on app/src/main/java/com/intive/patronage22/lublin/repository/model/GetProductResponse.kt
> +    @SerializedName("title")
> for custom names we can use `@JsonProperty`

will json work if i already use gson?

2022-04-05 11:40 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/screens/home/HomeListAdapter.kt
> +class HomeListAdapter(private val fragment: HomeFragment) :
in next PR please remove Fragment from here, for Glide loading you can simply use binding.root Context.

2022-04-05 13:22 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/repository/model/GetProductResponse.kt
> +    @SerializedName("title")
ok, let's keep as is

2022-04-06 11:11 UTC, dziubinski-intive commented on app/src/main/java/com/intive/patronage22/lublin/data/repository/ProductRepository.kt
> +    suspend fun getAllProducts() = patronageService.getAllProducts()
shouldn't Mapper act here to map API models to domain model?

2022-04-07 10:22 UTC, gdziubinski-vimn approved these changes
Small comment regarding rename added. Apart from this LGTM

2022-04-07 10:22 UTC, gdziubinski-vimn commented on app/src/main/java/com/intive/patronage22/lublin/data/api/PatronageService.kt
> +    suspend fun getAllProducts(): List<GetProductResponseApi>
Please replace the name to be `ProductApi`
Multiple times had an impression `GetProductResponseApi` corresponds to single product response.

2022-04-08 08:02 UTC, dziubinski-intive approved these changes

2022-04-08 08:03 UTC, merged